
//Next just_tree_struct
struct_tree{
    humans{
        human1
        {
            id      0
            name    "Alex"
            age     21
            from    "Earth"
        },
        human2
        {
            id      1
            name    "Jessy"
            age     19
            from    "Earth"
        }
    }
    //From ID component
    students {
        0, 1
    }
}

//Next just_tree_array (Single Type)
strings  
{
    "This is text 1"
    "This is text 2"
    "This is text 3"
}

numbers
{
    //There numbers
    1
    2
    3
}

reals
{
    //There floating points
    1.0
    2.0
    3.33333333333333333
}

bools
{
    //There bools
    false
    true
}

mix
{
    //There mix memeber (number and next floating point)
    1
    2.0
    3
}
